#!/bin/bash
set -euo pipefail

for file in config.sh oidc/setup_keycloak_{realm,user_roles}.sh
do
    docker cp ${file} oidc:/opt/jboss/$( basename ${file} )
done

docker exec oidc /opt/jboss/setup_keycloak_realm.sh > config.out
docker-compose restart oidc_kc
sleep 20
docker exec oidc /opt/jboss/setup_keycloak_user_roles.sh >> config.out
